// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function thing(aOpt, b, c) {
  var a = aOpt !== undefined ? aOpt : 1;
  return (a + b | 0) + c | 0;
}

console.log(thing(undefined, 3, 2));

function r(param) {
  return 3;
}

function r$prime(param) {
  return 3;
}

console.log(3);

console.log(3);

exports.thing = thing;
exports.r = r;
exports.r$prime = r$prime;
/*  Not a pure module */
